#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 84
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 46
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_LBRACE = 1,
  anon_sym_RBRACE = 2,
  anon_sym_import = 3,
  anon_sym_from = 4,
  anon_sym_as = 5,
  anon_sym_export = 6,
  anon_sym_LT = 7,
  anon_sym_COMMA = 8,
  anon_sym_GT = 9,
  anon_sym_COLON = 10,
  anon_sym_PLUS = 11,
  anon_sym_enum = 12,
  anon_sym_DOT = 13,
  anon_sym_LPAREN = 14,
  anon_sym_RPAREN = 15,
  anon_sym_if = 16,
  anon_sym_elseif = 17,
  anon_sym_else = 18,
  anon_sym_AT = 19,
  sym_ident = 20,
  sym_number = 21,
  sym_string = 22,
  sym_module = 23,
  sym__expression = 24,
  sym_block = 25,
  sym_import = 26,
  sym__import_name = 27,
  sym__import_name_alias = 28,
  sym_export = 29,
  sym_elp_type = 30,
  sym_elp_type_generic = 31,
  sym_elp_type_generic_param = 32,
  sym_elp_type_generic_constraint = 33,
  sym_enum = 34,
  sym_enum_member = 35,
  sym_if_tree = 36,
  sym_elseif_tree = 37,
  sym_else_block = 38,
  sym_macro = 39,
  aux_sym_module_repeat1 = 40,
  aux_sym_import_repeat1 = 41,
  aux_sym_elp_type_generic_repeat1 = 42,
  aux_sym_enum_repeat1 = 43,
  aux_sym_enum_member_repeat1 = 44,
  aux_sym_if_tree_repeat1 = 45,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_import] = "import",
  [anon_sym_from] = "from",
  [anon_sym_as] = "as",
  [anon_sym_export] = "export",
  [anon_sym_LT] = "<",
  [anon_sym_COMMA] = ",",
  [anon_sym_GT] = ">",
  [anon_sym_COLON] = ":",
  [anon_sym_PLUS] = "+",
  [anon_sym_enum] = "enum",
  [anon_sym_DOT] = ".",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_if] = "if",
  [anon_sym_elseif] = "elseif",
  [anon_sym_else] = "else",
  [anon_sym_AT] = "@",
  [sym_ident] = "ident",
  [sym_number] = "number",
  [sym_string] = "string",
  [sym_module] = "module",
  [sym__expression] = "_expression",
  [sym_block] = "block",
  [sym_import] = "import",
  [sym__import_name] = "_import_name",
  [sym__import_name_alias] = "_import_name_alias",
  [sym_export] = "export",
  [sym_elp_type] = "elp_type",
  [sym_elp_type_generic] = "elp_type_generic",
  [sym_elp_type_generic_param] = "elp_type_generic_param",
  [sym_elp_type_generic_constraint] = "elp_type_generic_constraint",
  [sym_enum] = "enum",
  [sym_enum_member] = "enum_member",
  [sym_if_tree] = "if_tree",
  [sym_elseif_tree] = "elseif_tree",
  [sym_else_block] = "else_block",
  [sym_macro] = "macro",
  [aux_sym_module_repeat1] = "module_repeat1",
  [aux_sym_import_repeat1] = "import_repeat1",
  [aux_sym_elp_type_generic_repeat1] = "elp_type_generic_repeat1",
  [aux_sym_enum_repeat1] = "enum_repeat1",
  [aux_sym_enum_member_repeat1] = "enum_member_repeat1",
  [aux_sym_if_tree_repeat1] = "if_tree_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_from] = anon_sym_from,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_export] = anon_sym_export,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_enum] = anon_sym_enum,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_elseif] = anon_sym_elseif,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_AT] = anon_sym_AT,
  [sym_ident] = sym_ident,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [sym_module] = sym_module,
  [sym__expression] = sym__expression,
  [sym_block] = sym_block,
  [sym_import] = sym_import,
  [sym__import_name] = sym__import_name,
  [sym__import_name_alias] = sym__import_name_alias,
  [sym_export] = sym_export,
  [sym_elp_type] = sym_elp_type,
  [sym_elp_type_generic] = sym_elp_type_generic,
  [sym_elp_type_generic_param] = sym_elp_type_generic_param,
  [sym_elp_type_generic_constraint] = sym_elp_type_generic_constraint,
  [sym_enum] = sym_enum,
  [sym_enum_member] = sym_enum_member,
  [sym_if_tree] = sym_if_tree,
  [sym_elseif_tree] = sym_elseif_tree,
  [sym_else_block] = sym_else_block,
  [sym_macro] = sym_macro,
  [aux_sym_module_repeat1] = aux_sym_module_repeat1,
  [aux_sym_import_repeat1] = aux_sym_import_repeat1,
  [aux_sym_elp_type_generic_repeat1] = aux_sym_elp_type_generic_repeat1,
  [aux_sym_enum_repeat1] = aux_sym_enum_repeat1,
  [aux_sym_enum_member_repeat1] = aux_sym_enum_member_repeat1,
  [aux_sym_if_tree_repeat1] = aux_sym_if_tree_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_from] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_export] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_enum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_elseif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_module] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_import] = {
    .visible = true,
    .named = true,
  },
  [sym__import_name] = {
    .visible = false,
    .named = true,
  },
  [sym__import_name_alias] = {
    .visible = false,
    .named = true,
  },
  [sym_export] = {
    .visible = true,
    .named = true,
  },
  [sym_elp_type] = {
    .visible = true,
    .named = true,
  },
  [sym_elp_type_generic] = {
    .visible = true,
    .named = true,
  },
  [sym_elp_type_generic_param] = {
    .visible = true,
    .named = true,
  },
  [sym_elp_type_generic_constraint] = {
    .visible = true,
    .named = true,
  },
  [sym_enum] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_member] = {
    .visible = true,
    .named = true,
  },
  [sym_if_tree] = {
    .visible = true,
    .named = true,
  },
  [sym_elseif_tree] = {
    .visible = true,
    .named = true,
  },
  [sym_else_block] = {
    .visible = true,
    .named = true,
  },
  [sym_macro] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_module_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_import_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_elp_type_generic_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_enum_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_enum_member_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_if_tree_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(23);
      ADVANCE_MAP(
        '"', 1,
        '(', 38,
        ')', 39,
        '+', 35,
        ',', 32,
        '.', 37,
        ':', 34,
        '<', 31,
        '>', 33,
        '@', 43,
        'a', 18,
        'e', 7,
        'f', 15,
        'i', 5,
        '{', 24,
        '}', 25,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(47);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == ')') ADVANCE(39);
      if (lookahead == '>') ADVANCE(33);
      if (lookahead == '}') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(44);
      if (lookahead == '}') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(42);
      END_STATE();
    case 5:
      if (lookahead == 'f') ADVANCE(40);
      if (lookahead == 'm') ADVANCE(14);
      END_STATE();
    case 6:
      if (lookahead == 'f') ADVANCE(41);
      END_STATE();
    case 7:
      if (lookahead == 'l') ADVANCE(19);
      if (lookahead == 'n') ADVANCE(22);
      if (lookahead == 'x') ADVANCE(13);
      END_STATE();
    case 8:
      if (lookahead == 'm') ADVANCE(36);
      END_STATE();
    case 9:
      if (lookahead == 'm') ADVANCE(27);
      END_STATE();
    case 10:
      if (lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 11:
      if (lookahead == 'o') ADVANCE(9);
      END_STATE();
    case 12:
      if (lookahead == 'o') ADVANCE(17);
      END_STATE();
    case 13:
      if (lookahead == 'p') ADVANCE(10);
      END_STATE();
    case 14:
      if (lookahead == 'p') ADVANCE(12);
      END_STATE();
    case 15:
      if (lookahead == 'r') ADVANCE(11);
      END_STATE();
    case 16:
      if (lookahead == 'r') ADVANCE(20);
      END_STATE();
    case 17:
      if (lookahead == 'r') ADVANCE(21);
      END_STATE();
    case 18:
      if (lookahead == 's') ADVANCE(28);
      END_STATE();
    case 19:
      if (lookahead == 's') ADVANCE(4);
      END_STATE();
    case 20:
      if (lookahead == 't') ADVANCE(30);
      END_STATE();
    case 21:
      if (lookahead == 't') ADVANCE(26);
      END_STATE();
    case 22:
      if (lookahead == 'u') ADVANCE(8);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_from);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_as);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_export);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_enum);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_elseif);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_else);
      if (lookahead == 'i') ADVANCE(6);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 's') ADVANCE(29);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_ident);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 2},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 2},
  [70] = {.lex_state = 2},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 2},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 2},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 2},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 2},
  [83] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_from] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_export] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_enum] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_elseif] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
  },
  [1] = {
    [sym_module] = STATE(73),
    [sym__expression] = STATE(4),
    [sym_block] = STATE(4),
    [sym_import] = STATE(4),
    [sym_export] = STATE(4),
    [sym_enum] = STATE(4),
    [sym_if_tree] = STATE(4),
    [sym_macro] = STATE(4),
    [aux_sym_module_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(5),
    [anon_sym_import] = ACTIONS(7),
    [anon_sym_export] = ACTIONS(9),
    [anon_sym_enum] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_AT] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [sym_string] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(24), 1,
      anon_sym_import,
    ACTIONS(27), 1,
      anon_sym_export,
    ACTIONS(30), 1,
      anon_sym_enum,
    ACTIONS(33), 1,
      anon_sym_if,
    ACTIONS(36), 1,
      anon_sym_AT,
    ACTIONS(19), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(39), 2,
      sym_number,
      sym_string,
    STATE(2), 8,
      sym__expression,
      sym_block,
      sym_import,
      sym_export,
      sym_enum,
      sym_if_tree,
      sym_macro,
      aux_sym_module_repeat1,
  [37] = 9,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      anon_sym_import,
    ACTIONS(9), 1,
      anon_sym_export,
    ACTIONS(11), 1,
      anon_sym_enum,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_AT,
    ACTIONS(42), 1,
      anon_sym_RBRACE,
    ACTIONS(44), 2,
      sym_number,
      sym_string,
    STATE(5), 8,
      sym__expression,
      sym_block,
      sym_import,
      sym_export,
      sym_enum,
      sym_if_tree,
      sym_macro,
      aux_sym_module_repeat1,
  [73] = 9,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      anon_sym_import,
    ACTIONS(9), 1,
      anon_sym_export,
    ACTIONS(11), 1,
      anon_sym_enum,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_AT,
    ACTIONS(46), 1,
      ts_builtin_sym_end,
    ACTIONS(48), 2,
      sym_number,
      sym_string,
    STATE(2), 8,
      sym__expression,
      sym_block,
      sym_import,
      sym_export,
      sym_enum,
      sym_if_tree,
      sym_macro,
      aux_sym_module_repeat1,
  [109] = 9,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      anon_sym_import,
    ACTIONS(9), 1,
      anon_sym_export,
    ACTIONS(11), 1,
      anon_sym_enum,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_AT,
    ACTIONS(50), 1,
      anon_sym_RBRACE,
    ACTIONS(48), 2,
      sym_number,
      sym_string,
    STATE(2), 8,
      sym__expression,
      sym_block,
      sym_import,
      sym_export,
      sym_enum,
      sym_if_tree,
      sym_macro,
      aux_sym_module_repeat1,
  [145] = 8,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      anon_sym_import,
    ACTIONS(9), 1,
      anon_sym_export,
    ACTIONS(11), 1,
      anon_sym_enum,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_AT,
    ACTIONS(52), 2,
      sym_number,
      sym_string,
    STATE(19), 7,
      sym__expression,
      sym_block,
      sym_import,
      sym_export,
      sym_enum,
      sym_if_tree,
      sym_macro,
  [177] = 5,
    ACTIONS(56), 1,
      anon_sym_elseif,
    ACTIONS(58), 1,
      anon_sym_else,
    STATE(22), 1,
      sym_else_block,
    STATE(11), 2,
      sym_elseif_tree,
      aux_sym_if_tree_repeat1,
    ACTIONS(54), 10,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_export,
      anon_sym_enum,
      anon_sym_if,
      anon_sym_AT,
      sym_number,
      sym_string,
  [203] = 8,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      anon_sym_import,
    ACTIONS(9), 1,
      anon_sym_export,
    ACTIONS(11), 1,
      anon_sym_enum,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_AT,
    ACTIONS(60), 2,
      sym_number,
      sym_string,
    STATE(59), 7,
      sym__expression,
      sym_block,
      sym_import,
      sym_export,
      sym_enum,
      sym_if_tree,
      sym_macro,
  [235] = 5,
    ACTIONS(56), 1,
      anon_sym_elseif,
    ACTIONS(58), 1,
      anon_sym_else,
    STATE(16), 1,
      sym_else_block,
    STATE(7), 2,
      sym_elseif_tree,
      aux_sym_if_tree_repeat1,
    ACTIONS(62), 10,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_export,
      anon_sym_enum,
      anon_sym_if,
      anon_sym_AT,
      sym_number,
      sym_string,
  [261] = 8,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      anon_sym_import,
    ACTIONS(9), 1,
      anon_sym_export,
    ACTIONS(11), 1,
      anon_sym_enum,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_AT,
    ACTIONS(64), 2,
      sym_number,
      sym_string,
    STATE(57), 7,
      sym__expression,
      sym_block,
      sym_import,
      sym_export,
      sym_enum,
      sym_if_tree,
      sym_macro,
  [293] = 4,
    ACTIONS(68), 1,
      anon_sym_elseif,
    ACTIONS(71), 1,
      anon_sym_else,
    STATE(11), 2,
      sym_elseif_tree,
      aux_sym_if_tree_repeat1,
    ACTIONS(66), 10,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_export,
      anon_sym_enum,
      anon_sym_if,
      anon_sym_AT,
      sym_number,
      sym_string,
  [316] = 2,
    ACTIONS(75), 1,
      anon_sym_else,
    ACTIONS(73), 11,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_export,
      anon_sym_enum,
      anon_sym_if,
      anon_sym_elseif,
      anon_sym_AT,
      sym_number,
      sym_string,
  [333] = 2,
    ACTIONS(79), 1,
      anon_sym_else,
    ACTIONS(77), 11,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_export,
      anon_sym_enum,
      anon_sym_if,
      anon_sym_elseif,
      anon_sym_AT,
      sym_number,
      sym_string,
  [350] = 2,
    ACTIONS(83), 1,
      anon_sym_else,
    ACTIONS(81), 11,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_export,
      anon_sym_enum,
      anon_sym_if,
      anon_sym_elseif,
      anon_sym_AT,
      sym_number,
      sym_string,
  [367] = 1,
    ACTIONS(85), 10,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_export,
      anon_sym_enum,
      anon_sym_if,
      anon_sym_AT,
      sym_number,
      sym_string,
  [380] = 1,
    ACTIONS(54), 10,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_export,
      anon_sym_enum,
      anon_sym_if,
      anon_sym_AT,
      sym_number,
      sym_string,
  [393] = 1,
    ACTIONS(87), 10,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_export,
      anon_sym_enum,
      anon_sym_if,
      anon_sym_AT,
      sym_number,
      sym_string,
  [406] = 1,
    ACTIONS(89), 10,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_export,
      anon_sym_enum,
      anon_sym_if,
      anon_sym_AT,
      sym_number,
      sym_string,
  [419] = 1,
    ACTIONS(91), 10,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_export,
      anon_sym_enum,
      anon_sym_if,
      anon_sym_AT,
      sym_number,
      sym_string,
  [432] = 1,
    ACTIONS(93), 10,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_export,
      anon_sym_enum,
      anon_sym_if,
      anon_sym_AT,
      sym_number,
      sym_string,
  [445] = 1,
    ACTIONS(95), 10,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_export,
      anon_sym_enum,
      anon_sym_if,
      anon_sym_AT,
      sym_number,
      sym_string,
  [458] = 1,
    ACTIONS(97), 10,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_export,
      anon_sym_enum,
      anon_sym_if,
      anon_sym_AT,
      sym_number,
      sym_string,
  [471] = 1,
    ACTIONS(99), 10,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_export,
      anon_sym_enum,
      anon_sym_if,
      anon_sym_AT,
      sym_number,
      sym_string,
  [484] = 1,
    ACTIONS(101), 10,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_export,
      anon_sym_enum,
      anon_sym_if,
      anon_sym_AT,
      sym_number,
      sym_string,
  [497] = 1,
    ACTIONS(103), 10,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_export,
      anon_sym_enum,
      anon_sym_if,
      anon_sym_AT,
      sym_number,
      sym_string,
  [510] = 1,
    ACTIONS(105), 10,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_export,
      anon_sym_enum,
      anon_sym_if,
      anon_sym_AT,
      sym_number,
      sym_string,
  [523] = 1,
    ACTIONS(107), 5,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_RPAREN,
  [531] = 1,
    ACTIONS(109), 5,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_RPAREN,
  [539] = 1,
    ACTIONS(111), 5,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_RPAREN,
  [547] = 1,
    ACTIONS(113), 5,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_RPAREN,
  [555] = 3,
    ACTIONS(115), 1,
      anon_sym_RBRACE,
    ACTIONS(117), 1,
      sym_ident,
    STATE(34), 2,
      sym__import_name,
      aux_sym_import_repeat1,
  [566] = 3,
    ACTIONS(117), 1,
      sym_ident,
    ACTIONS(119), 1,
      anon_sym_RBRACE,
    STATE(31), 2,
      sym__import_name,
      aux_sym_import_repeat1,
  [577] = 4,
    ACTIONS(121), 1,
      anon_sym_RBRACE,
    ACTIONS(123), 1,
      anon_sym_as,
    ACTIONS(125), 1,
      sym_ident,
    STATE(55), 1,
      sym__import_name_alias,
  [590] = 3,
    ACTIONS(127), 1,
      anon_sym_RBRACE,
    ACTIONS(129), 1,
      sym_ident,
    STATE(34), 2,
      sym__import_name,
      aux_sym_import_repeat1,
  [601] = 4,
    ACTIONS(132), 1,
      anon_sym_GT,
    ACTIONS(134), 1,
      sym_ident,
    STATE(36), 1,
      sym_elp_type,
    STATE(46), 1,
      sym_elp_type_generic_param,
  [614] = 3,
    ACTIONS(138), 1,
      anon_sym_COLON,
    STATE(65), 1,
      sym_elp_type_generic_constraint,
    ACTIONS(136), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [625] = 3,
    ACTIONS(140), 1,
      anon_sym_COMMA,
    ACTIONS(142), 1,
      anon_sym_RPAREN,
    STATE(47), 1,
      aux_sym_enum_member_repeat1,
  [635] = 3,
    ACTIONS(140), 1,
      anon_sym_COMMA,
    ACTIONS(144), 1,
      anon_sym_RPAREN,
    STATE(41), 1,
      aux_sym_enum_member_repeat1,
  [645] = 2,
    ACTIONS(148), 1,
      anon_sym_LPAREN,
    ACTIONS(146), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [653] = 3,
    ACTIONS(150), 1,
      anon_sym_RBRACE,
    ACTIONS(152), 1,
      anon_sym_COMMA,
    STATE(44), 1,
      aux_sym_enum_repeat1,
  [663] = 3,
    ACTIONS(140), 1,
      anon_sym_COMMA,
    ACTIONS(154), 1,
      anon_sym_RPAREN,
    STATE(47), 1,
      aux_sym_enum_member_repeat1,
  [673] = 3,
    ACTIONS(152), 1,
      anon_sym_COMMA,
    ACTIONS(156), 1,
      anon_sym_RBRACE,
    STATE(40), 1,
      aux_sym_enum_repeat1,
  [683] = 3,
    ACTIONS(134), 1,
      sym_ident,
    ACTIONS(158), 1,
      anon_sym_RPAREN,
    STATE(48), 1,
      sym_elp_type,
  [693] = 3,
    ACTIONS(160), 1,
      anon_sym_RBRACE,
    ACTIONS(162), 1,
      anon_sym_COMMA,
    STATE(44), 1,
      aux_sym_enum_repeat1,
  [703] = 3,
    ACTIONS(165), 1,
      anon_sym_RBRACE,
    ACTIONS(167), 1,
      anon_sym_DOT,
    STATE(42), 1,
      sym_enum_member,
  [713] = 3,
    ACTIONS(169), 1,
      anon_sym_COMMA,
    ACTIONS(171), 1,
      anon_sym_GT,
    STATE(51), 1,
      aux_sym_elp_type_generic_repeat1,
  [723] = 3,
    ACTIONS(173), 1,
      anon_sym_COMMA,
    ACTIONS(176), 1,
      anon_sym_RPAREN,
    STATE(47), 1,
      aux_sym_enum_member_repeat1,
  [733] = 3,
    ACTIONS(140), 1,
      anon_sym_COMMA,
    ACTIONS(178), 1,
      anon_sym_RPAREN,
    STATE(37), 1,
      aux_sym_enum_member_repeat1,
  [743] = 3,
    ACTIONS(134), 1,
      sym_ident,
    STATE(36), 1,
      sym_elp_type,
    STATE(67), 1,
      sym_elp_type_generic_param,
  [753] = 3,
    ACTIONS(134), 1,
      sym_ident,
    ACTIONS(180), 1,
      anon_sym_RPAREN,
    STATE(38), 1,
      sym_elp_type,
  [763] = 3,
    ACTIONS(169), 1,
      anon_sym_COMMA,
    ACTIONS(182), 1,
      anon_sym_GT,
    STATE(53), 1,
      aux_sym_elp_type_generic_repeat1,
  [773] = 2,
    ACTIONS(186), 1,
      anon_sym_PLUS,
    ACTIONS(184), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [781] = 3,
    ACTIONS(188), 1,
      anon_sym_COMMA,
    ACTIONS(191), 1,
      anon_sym_GT,
    STATE(53), 1,
      aux_sym_elp_type_generic_repeat1,
  [791] = 1,
    ACTIONS(160), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [796] = 1,
    ACTIONS(193), 2,
      anon_sym_RBRACE,
      sym_ident,
  [801] = 1,
    ACTIONS(176), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [806] = 2,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    STATE(14), 1,
      sym_block,
  [813] = 2,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    STATE(21), 1,
      sym_block,
  [820] = 2,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    STATE(9), 1,
      sym_block,
  [827] = 2,
    ACTIONS(167), 1,
      anon_sym_DOT,
    STATE(54), 1,
      sym_enum_member,
  [834] = 1,
    ACTIONS(195), 2,
      anon_sym_RBRACE,
      sym_ident,
  [839] = 1,
    ACTIONS(197), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [844] = 1,
    ACTIONS(199), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [849] = 2,
    ACTIONS(134), 1,
      sym_ident,
    STATE(52), 1,
      sym_elp_type,
  [856] = 1,
    ACTIONS(201), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [861] = 1,
    ACTIONS(203), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [866] = 1,
    ACTIONS(191), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [871] = 2,
    ACTIONS(205), 1,
      anon_sym_LT,
    STATE(28), 1,
      sym_elp_type_generic,
  [878] = 2,
    ACTIONS(134), 1,
      sym_ident,
    STATE(56), 1,
      sym_elp_type,
  [885] = 2,
    ACTIONS(134), 1,
      sym_ident,
    STATE(71), 1,
      sym_elp_type,
  [892] = 1,
    ACTIONS(207), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [897] = 1,
    ACTIONS(209), 1,
      sym_ident,
  [901] = 1,
    ACTIONS(211), 1,
      ts_builtin_sym_end,
  [905] = 1,
    ACTIONS(213), 1,
      sym_ident,
  [909] = 1,
    ACTIONS(215), 1,
      sym_string,
  [913] = 1,
    ACTIONS(217), 1,
      anon_sym_LBRACE,
  [917] = 1,
    ACTIONS(219), 1,
      sym_string,
  [921] = 1,
    ACTIONS(221), 1,
      anon_sym_LBRACE,
  [925] = 1,
    ACTIONS(223), 1,
      sym_ident,
  [929] = 1,
    ACTIONS(225), 1,
      anon_sym_from,
  [933] = 1,
    ACTIONS(227), 1,
      anon_sym_LPAREN,
  [937] = 1,
    ACTIONS(229), 1,
      sym_ident,
  [941] = 1,
    ACTIONS(231), 1,
      anon_sym_from,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 37,
  [SMALL_STATE(4)] = 73,
  [SMALL_STATE(5)] = 109,
  [SMALL_STATE(6)] = 145,
  [SMALL_STATE(7)] = 177,
  [SMALL_STATE(8)] = 203,
  [SMALL_STATE(9)] = 235,
  [SMALL_STATE(10)] = 261,
  [SMALL_STATE(11)] = 293,
  [SMALL_STATE(12)] = 316,
  [SMALL_STATE(13)] = 333,
  [SMALL_STATE(14)] = 350,
  [SMALL_STATE(15)] = 367,
  [SMALL_STATE(16)] = 380,
  [SMALL_STATE(17)] = 393,
  [SMALL_STATE(18)] = 406,
  [SMALL_STATE(19)] = 419,
  [SMALL_STATE(20)] = 432,
  [SMALL_STATE(21)] = 445,
  [SMALL_STATE(22)] = 458,
  [SMALL_STATE(23)] = 471,
  [SMALL_STATE(24)] = 484,
  [SMALL_STATE(25)] = 497,
  [SMALL_STATE(26)] = 510,
  [SMALL_STATE(27)] = 523,
  [SMALL_STATE(28)] = 531,
  [SMALL_STATE(29)] = 539,
  [SMALL_STATE(30)] = 547,
  [SMALL_STATE(31)] = 555,
  [SMALL_STATE(32)] = 566,
  [SMALL_STATE(33)] = 577,
  [SMALL_STATE(34)] = 590,
  [SMALL_STATE(35)] = 601,
  [SMALL_STATE(36)] = 614,
  [SMALL_STATE(37)] = 625,
  [SMALL_STATE(38)] = 635,
  [SMALL_STATE(39)] = 645,
  [SMALL_STATE(40)] = 653,
  [SMALL_STATE(41)] = 663,
  [SMALL_STATE(42)] = 673,
  [SMALL_STATE(43)] = 683,
  [SMALL_STATE(44)] = 693,
  [SMALL_STATE(45)] = 703,
  [SMALL_STATE(46)] = 713,
  [SMALL_STATE(47)] = 723,
  [SMALL_STATE(48)] = 733,
  [SMALL_STATE(49)] = 743,
  [SMALL_STATE(50)] = 753,
  [SMALL_STATE(51)] = 763,
  [SMALL_STATE(52)] = 773,
  [SMALL_STATE(53)] = 781,
  [SMALL_STATE(54)] = 791,
  [SMALL_STATE(55)] = 796,
  [SMALL_STATE(56)] = 801,
  [SMALL_STATE(57)] = 806,
  [SMALL_STATE(58)] = 813,
  [SMALL_STATE(59)] = 820,
  [SMALL_STATE(60)] = 827,
  [SMALL_STATE(61)] = 834,
  [SMALL_STATE(62)] = 839,
  [SMALL_STATE(63)] = 844,
  [SMALL_STATE(64)] = 849,
  [SMALL_STATE(65)] = 856,
  [SMALL_STATE(66)] = 861,
  [SMALL_STATE(67)] = 866,
  [SMALL_STATE(68)] = 871,
  [SMALL_STATE(69)] = 878,
  [SMALL_STATE(70)] = 885,
  [SMALL_STATE(71)] = 892,
  [SMALL_STATE(72)] = 897,
  [SMALL_STATE(73)] = 901,
  [SMALL_STATE(74)] = 905,
  [SMALL_STATE(75)] = 909,
  [SMALL_STATE(76)] = 913,
  [SMALL_STATE(77)] = 917,
  [SMALL_STATE(78)] = 921,
  [SMALL_STATE(79)] = 925,
  [SMALL_STATE(80)] = 929,
  [SMALL_STATE(81)] = 933,
  [SMALL_STATE(82)] = 937,
  [SMALL_STATE(83)] = 941,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0), SHIFT_REPEAT(76),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0), SHIFT_REPEAT(72),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_tree, 4, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_tree, 3, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_if_tree_repeat1, 2, 0, 0),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_if_tree_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_if_tree_repeat1, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_elseif_tree, 3, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_elseif_tree, 3, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 5, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro, 4, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum, 4, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_export, 2, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum, 5, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_else_block, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_tree, 5, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 6, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum, 6, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro, 5, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro, 6, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_elp_type_generic, 4, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_elp_type, 2, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_elp_type_generic, 2, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_elp_type_generic, 3, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__import_name, 1, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__import_name, 1, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_import_repeat1, 2, 0, 0),
  [129] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_import_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_elp_type_generic_param, 1, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_member, 2, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_repeat1, 2, 0, 0),
  [162] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enum_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [173] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enum_member_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_member_repeat1, 2, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_elp_type_generic_constraint, 2, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [188] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_elp_type_generic_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_elp_type_generic_repeat1, 2, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__import_name, 2, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__import_name_alias, 2, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_member, 4, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_member, 6, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_elp_type_generic_param, 2, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_member, 5, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_elp_type_generic_constraint, 4, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [211] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_elp(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
