#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 132
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 59
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_LBRACE = 1,
  anon_sym_RBRACE = 2,
  anon_sym_import = 3,
  anon_sym_COMMA = 4,
  anon_sym_from = 5,
  anon_sym_as = 6,
  anon_sym_export = 7,
  anon_sym_LT = 8,
  anon_sym_GT = 9,
  anon_sym_COLON = 10,
  anon_sym_PLUS = 11,
  anon_sym_enum = 12,
  anon_sym_DOT = 13,
  anon_sym_LPAREN = 14,
  anon_sym_RPAREN = 15,
  anon_sym_if = 16,
  anon_sym_elseif = 17,
  anon_sym_else = 18,
  anon_sym_AT = 19,
  anon_sym_object = 20,
  anon_sym_implements = 21,
  anon_sym_public = 22,
  anon_sym_private = 23,
  anon_sym_EQ = 24,
  anon_sym_BQUOTE = 25,
  sym_ident = 26,
  sym_number = 27,
  sym_string = 28,
  sym_module = 29,
  sym__expression = 30,
  sym_block = 31,
  sym_import = 32,
  sym__import_name = 33,
  sym__import_name_alias = 34,
  sym_export = 35,
  sym_elp_type = 36,
  sym_elp_type_generic = 37,
  sym_elp_type_generic_param = 38,
  sym_elp_type_generic_constraint = 39,
  sym_enum = 40,
  sym_enum_member = 41,
  sym_if_tree = 42,
  sym_elseif_tree = 43,
  sym_else_block = 44,
  sym_macro = 45,
  sym_object_def = 46,
  sym_object_implements = 47,
  sym_object_member = 48,
  sym_object_key_default_value = 49,
  sym_object_key_tags = 50,
  aux_sym_module_repeat1 = 51,
  aux_sym_import_repeat1 = 52,
  aux_sym_elp_type_generic_repeat1 = 53,
  aux_sym_enum_repeat1 = 54,
  aux_sym_enum_member_repeat1 = 55,
  aux_sym_if_tree_repeat1 = 56,
  aux_sym_object_def_repeat1 = 57,
  aux_sym_object_key_tags_repeat1 = 58,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_import] = "import",
  [anon_sym_COMMA] = ",",
  [anon_sym_from] = "from",
  [anon_sym_as] = "as",
  [anon_sym_export] = "export",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_COLON] = ":",
  [anon_sym_PLUS] = "+",
  [anon_sym_enum] = "enum",
  [anon_sym_DOT] = ".",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_if] = "if",
  [anon_sym_elseif] = "elseif",
  [anon_sym_else] = "else",
  [anon_sym_AT] = "@",
  [anon_sym_object] = "object",
  [anon_sym_implements] = "implements",
  [anon_sym_public] = "public",
  [anon_sym_private] = "private",
  [anon_sym_EQ] = "=",
  [anon_sym_BQUOTE] = "`",
  [sym_ident] = "ident",
  [sym_number] = "number",
  [sym_string] = "string",
  [sym_module] = "module",
  [sym__expression] = "_expression",
  [sym_block] = "block",
  [sym_import] = "import",
  [sym__import_name] = "_import_name",
  [sym__import_name_alias] = "_import_name_alias",
  [sym_export] = "export",
  [sym_elp_type] = "elp_type",
  [sym_elp_type_generic] = "elp_type_generic",
  [sym_elp_type_generic_param] = "elp_type_generic_param",
  [sym_elp_type_generic_constraint] = "elp_type_generic_constraint",
  [sym_enum] = "enum",
  [sym_enum_member] = "enum_member",
  [sym_if_tree] = "if_tree",
  [sym_elseif_tree] = "elseif_tree",
  [sym_else_block] = "else_block",
  [sym_macro] = "macro",
  [sym_object_def] = "object_def",
  [sym_object_implements] = "object_implements",
  [sym_object_member] = "object_member",
  [sym_object_key_default_value] = "object_key_default_value",
  [sym_object_key_tags] = "object_key_tags",
  [aux_sym_module_repeat1] = "module_repeat1",
  [aux_sym_import_repeat1] = "import_repeat1",
  [aux_sym_elp_type_generic_repeat1] = "elp_type_generic_repeat1",
  [aux_sym_enum_repeat1] = "enum_repeat1",
  [aux_sym_enum_member_repeat1] = "enum_member_repeat1",
  [aux_sym_if_tree_repeat1] = "if_tree_repeat1",
  [aux_sym_object_def_repeat1] = "object_def_repeat1",
  [aux_sym_object_key_tags_repeat1] = "object_key_tags_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_from] = anon_sym_from,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_export] = anon_sym_export,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_enum] = anon_sym_enum,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_elseif] = anon_sym_elseif,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_object] = anon_sym_object,
  [anon_sym_implements] = anon_sym_implements,
  [anon_sym_public] = anon_sym_public,
  [anon_sym_private] = anon_sym_private,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [sym_ident] = sym_ident,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [sym_module] = sym_module,
  [sym__expression] = sym__expression,
  [sym_block] = sym_block,
  [sym_import] = sym_import,
  [sym__import_name] = sym__import_name,
  [sym__import_name_alias] = sym__import_name_alias,
  [sym_export] = sym_export,
  [sym_elp_type] = sym_elp_type,
  [sym_elp_type_generic] = sym_elp_type_generic,
  [sym_elp_type_generic_param] = sym_elp_type_generic_param,
  [sym_elp_type_generic_constraint] = sym_elp_type_generic_constraint,
  [sym_enum] = sym_enum,
  [sym_enum_member] = sym_enum_member,
  [sym_if_tree] = sym_if_tree,
  [sym_elseif_tree] = sym_elseif_tree,
  [sym_else_block] = sym_else_block,
  [sym_macro] = sym_macro,
  [sym_object_def] = sym_object_def,
  [sym_object_implements] = sym_object_implements,
  [sym_object_member] = sym_object_member,
  [sym_object_key_default_value] = sym_object_key_default_value,
  [sym_object_key_tags] = sym_object_key_tags,
  [aux_sym_module_repeat1] = aux_sym_module_repeat1,
  [aux_sym_import_repeat1] = aux_sym_import_repeat1,
  [aux_sym_elp_type_generic_repeat1] = aux_sym_elp_type_generic_repeat1,
  [aux_sym_enum_repeat1] = aux_sym_enum_repeat1,
  [aux_sym_enum_member_repeat1] = aux_sym_enum_member_repeat1,
  [aux_sym_if_tree_repeat1] = aux_sym_if_tree_repeat1,
  [aux_sym_object_def_repeat1] = aux_sym_object_def_repeat1,
  [aux_sym_object_key_tags_repeat1] = aux_sym_object_key_tags_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_from] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_export] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_enum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_elseif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_object] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_implements] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_public] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_private] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_module] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_import] = {
    .visible = true,
    .named = true,
  },
  [sym__import_name] = {
    .visible = false,
    .named = true,
  },
  [sym__import_name_alias] = {
    .visible = false,
    .named = true,
  },
  [sym_export] = {
    .visible = true,
    .named = true,
  },
  [sym_elp_type] = {
    .visible = true,
    .named = true,
  },
  [sym_elp_type_generic] = {
    .visible = true,
    .named = true,
  },
  [sym_elp_type_generic_param] = {
    .visible = true,
    .named = true,
  },
  [sym_elp_type_generic_constraint] = {
    .visible = true,
    .named = true,
  },
  [sym_enum] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_member] = {
    .visible = true,
    .named = true,
  },
  [sym_if_tree] = {
    .visible = true,
    .named = true,
  },
  [sym_elseif_tree] = {
    .visible = true,
    .named = true,
  },
  [sym_else_block] = {
    .visible = true,
    .named = true,
  },
  [sym_macro] = {
    .visible = true,
    .named = true,
  },
  [sym_object_def] = {
    .visible = true,
    .named = true,
  },
  [sym_object_implements] = {
    .visible = true,
    .named = true,
  },
  [sym_object_member] = {
    .visible = true,
    .named = true,
  },
  [sym_object_key_default_value] = {
    .visible = true,
    .named = true,
  },
  [sym_object_key_tags] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_module_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_import_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_elp_type_generic_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_enum_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_enum_member_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_if_tree_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_object_def_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_object_key_tags_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(43);
      ADVANCE_MAP(
        '"', 1,
        '(', 57,
        ')', 58,
        '+', 54,
        ',', 47,
        '.', 56,
        ':', 53,
        '<', 51,
        '=', 67,
        '>', 52,
        '@', 62,
        '`', 68,
        'a', 33,
        'e', 18,
        'f', 29,
        'i', 13,
        'o', 4,
        'p', 30,
        '{', 44,
        '}', 45,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(71);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == ')') ADVANCE(58);
      if (lookahead == '>') ADVANCE(52);
      if (lookahead == '`') ADVANCE(68);
      if (lookahead == '{') ADVANCE(44);
      if (lookahead == '}') ADVANCE(45);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(40);
      END_STATE();
    case 4:
      if (lookahead == 'b') ADVANCE(17);
      END_STATE();
    case 5:
      if (lookahead == 'b') ADVANCE(19);
      END_STATE();
    case 6:
      if (lookahead == 'c') ADVANCE(65);
      END_STATE();
    case 7:
      if (lookahead == 'c') ADVANCE(38);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(61);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(7);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(66);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 13:
      if (lookahead == 'f') ADVANCE(59);
      if (lookahead == 'm') ADVANCE(27);
      END_STATE();
    case 14:
      if (lookahead == 'f') ADVANCE(60);
      END_STATE();
    case 15:
      if (lookahead == 'i') ADVANCE(42);
      END_STATE();
    case 16:
      if (lookahead == 'i') ADVANCE(6);
      END_STATE();
    case 17:
      if (lookahead == 'j') ADVANCE(9);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(34);
      if (lookahead == 'n') ADVANCE(41);
      if (lookahead == 'x') ADVANCE(28);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(16);
      END_STATE();
    case 20:
      if (lookahead == 'l') ADVANCE(12);
      if (lookahead == 'o') ADVANCE(32);
      END_STATE();
    case 21:
      if (lookahead == 'm') ADVANCE(55);
      END_STATE();
    case 22:
      if (lookahead == 'm') ADVANCE(48);
      END_STATE();
    case 23:
      if (lookahead == 'm') ADVANCE(10);
      END_STATE();
    case 24:
      if (lookahead == 'n') ADVANCE(39);
      END_STATE();
    case 25:
      if (lookahead == 'o') ADVANCE(31);
      END_STATE();
    case 26:
      if (lookahead == 'o') ADVANCE(22);
      END_STATE();
    case 27:
      if (lookahead == 'p') ADVANCE(20);
      END_STATE();
    case 28:
      if (lookahead == 'p') ADVANCE(25);
      END_STATE();
    case 29:
      if (lookahead == 'r') ADVANCE(26);
      END_STATE();
    case 30:
      if (lookahead == 'r') ADVANCE(15);
      if (lookahead == 'u') ADVANCE(5);
      END_STATE();
    case 31:
      if (lookahead == 'r') ADVANCE(36);
      END_STATE();
    case 32:
      if (lookahead == 'r') ADVANCE(37);
      END_STATE();
    case 33:
      if (lookahead == 's') ADVANCE(49);
      END_STATE();
    case 34:
      if (lookahead == 's') ADVANCE(8);
      END_STATE();
    case 35:
      if (lookahead == 's') ADVANCE(64);
      END_STATE();
    case 36:
      if (lookahead == 't') ADVANCE(50);
      END_STATE();
    case 37:
      if (lookahead == 't') ADVANCE(46);
      END_STATE();
    case 38:
      if (lookahead == 't') ADVANCE(63);
      END_STATE();
    case 39:
      if (lookahead == 't') ADVANCE(35);
      END_STATE();
    case 40:
      if (lookahead == 't') ADVANCE(11);
      END_STATE();
    case 41:
      if (lookahead == 'u') ADVANCE(21);
      END_STATE();
    case 42:
      if (lookahead == 'v') ADVANCE(3);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_from);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_export);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_enum);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_elseif);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_else);
      if (lookahead == 'i') ADVANCE(14);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_object);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_implements);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_public);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_private);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_ident);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 2},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 2},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 2},
  [88] = {.lex_state = 2},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 2},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 2},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 2},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 2},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 2},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 2},
  [117] = {.lex_state = 2},
  [118] = {.lex_state = 2},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 2},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 2},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 2},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 2},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 2},
  [131] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_from] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_export] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_enum] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_elseif] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_object] = ACTIONS(1),
    [anon_sym_implements] = ACTIONS(1),
    [anon_sym_public] = ACTIONS(1),
    [anon_sym_private] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
  },
  [1] = {
    [sym_module] = STATE(125),
    [sym__expression] = STATE(4),
    [sym_block] = STATE(4),
    [sym_import] = STATE(4),
    [sym_export] = STATE(4),
    [sym_enum] = STATE(4),
    [sym_if_tree] = STATE(4),
    [sym_macro] = STATE(4),
    [sym_object_def] = STATE(4),
    [aux_sym_module_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(5),
    [anon_sym_import] = ACTIONS(7),
    [anon_sym_export] = ACTIONS(9),
    [anon_sym_enum] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_AT] = ACTIONS(15),
    [anon_sym_object] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(26), 1,
      anon_sym_import,
    ACTIONS(29), 1,
      anon_sym_export,
    ACTIONS(32), 1,
      anon_sym_enum,
    ACTIONS(35), 1,
      anon_sym_if,
    ACTIONS(38), 1,
      anon_sym_AT,
    ACTIONS(41), 1,
      anon_sym_object,
    ACTIONS(21), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(44), 2,
      sym_number,
      sym_string,
    STATE(2), 9,
      sym__expression,
      sym_block,
      sym_import,
      sym_export,
      sym_enum,
      sym_if_tree,
      sym_macro,
      sym_object_def,
      aux_sym_module_repeat1,
  [41] = 10,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      anon_sym_import,
    ACTIONS(9), 1,
      anon_sym_export,
    ACTIONS(11), 1,
      anon_sym_enum,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      anon_sym_object,
    ACTIONS(47), 1,
      anon_sym_RBRACE,
    ACTIONS(49), 2,
      sym_number,
      sym_string,
    STATE(5), 9,
      sym__expression,
      sym_block,
      sym_import,
      sym_export,
      sym_enum,
      sym_if_tree,
      sym_macro,
      sym_object_def,
      aux_sym_module_repeat1,
  [81] = 10,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      anon_sym_import,
    ACTIONS(9), 1,
      anon_sym_export,
    ACTIONS(11), 1,
      anon_sym_enum,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      anon_sym_object,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    ACTIONS(53), 2,
      sym_number,
      sym_string,
    STATE(2), 9,
      sym__expression,
      sym_block,
      sym_import,
      sym_export,
      sym_enum,
      sym_if_tree,
      sym_macro,
      sym_object_def,
      aux_sym_module_repeat1,
  [121] = 10,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      anon_sym_import,
    ACTIONS(9), 1,
      anon_sym_export,
    ACTIONS(11), 1,
      anon_sym_enum,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      anon_sym_object,
    ACTIONS(55), 1,
      anon_sym_RBRACE,
    ACTIONS(53), 2,
      sym_number,
      sym_string,
    STATE(2), 9,
      sym__expression,
      sym_block,
      sym_import,
      sym_export,
      sym_enum,
      sym_if_tree,
      sym_macro,
      sym_object_def,
      aux_sym_module_repeat1,
  [161] = 5,
    ACTIONS(59), 1,
      anon_sym_elseif,
    ACTIONS(61), 1,
      anon_sym_else,
    STATE(23), 1,
      sym_else_block,
    STATE(11), 2,
      sym_elseif_tree,
      aux_sym_if_tree_repeat1,
    ACTIONS(57), 13,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_export,
      anon_sym_enum,
      anon_sym_if,
      anon_sym_AT,
      anon_sym_object,
      anon_sym_BQUOTE,
      sym_number,
      sym_string,
  [190] = 5,
    ACTIONS(59), 1,
      anon_sym_elseif,
    ACTIONS(61), 1,
      anon_sym_else,
    STATE(17), 1,
      sym_else_block,
    STATE(6), 2,
      sym_elseif_tree,
      aux_sym_if_tree_repeat1,
    ACTIONS(63), 13,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_export,
      anon_sym_enum,
      anon_sym_if,
      anon_sym_AT,
      anon_sym_object,
      anon_sym_BQUOTE,
      sym_number,
      sym_string,
  [219] = 9,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      anon_sym_import,
    ACTIONS(9), 1,
      anon_sym_export,
    ACTIONS(11), 1,
      anon_sym_enum,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      anon_sym_object,
    ACTIONS(65), 2,
      sym_number,
      sym_string,
    STATE(16), 8,
      sym__expression,
      sym_block,
      sym_import,
      sym_export,
      sym_enum,
      sym_if_tree,
      sym_macro,
      sym_object_def,
  [255] = 9,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      anon_sym_import,
    ACTIONS(9), 1,
      anon_sym_export,
    ACTIONS(11), 1,
      anon_sym_enum,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      anon_sym_object,
    ACTIONS(67), 2,
      sym_number,
      sym_string,
    STATE(84), 8,
      sym__expression,
      sym_block,
      sym_import,
      sym_export,
      sym_enum,
      sym_if_tree,
      sym_macro,
      sym_object_def,
  [291] = 9,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      anon_sym_import,
    ACTIONS(9), 1,
      anon_sym_export,
    ACTIONS(11), 1,
      anon_sym_enum,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      anon_sym_object,
    ACTIONS(69), 2,
      sym_number,
      sym_string,
    STATE(95), 8,
      sym__expression,
      sym_block,
      sym_import,
      sym_export,
      sym_enum,
      sym_if_tree,
      sym_macro,
      sym_object_def,
  [327] = 4,
    ACTIONS(73), 1,
      anon_sym_elseif,
    ACTIONS(76), 1,
      anon_sym_else,
    STATE(11), 2,
      sym_elseif_tree,
      aux_sym_if_tree_repeat1,
    ACTIONS(71), 13,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_export,
      anon_sym_enum,
      anon_sym_if,
      anon_sym_AT,
      anon_sym_object,
      anon_sym_BQUOTE,
      sym_number,
      sym_string,
  [353] = 9,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      anon_sym_import,
    ACTIONS(9), 1,
      anon_sym_export,
    ACTIONS(11), 1,
      anon_sym_enum,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      anon_sym_object,
    ACTIONS(78), 2,
      sym_number,
      sym_string,
    STATE(76), 8,
      sym__expression,
      sym_block,
      sym_import,
      sym_export,
      sym_enum,
      sym_if_tree,
      sym_macro,
      sym_object_def,
  [389] = 2,
    ACTIONS(82), 1,
      anon_sym_else,
    ACTIONS(80), 14,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_export,
      anon_sym_enum,
      anon_sym_if,
      anon_sym_elseif,
      anon_sym_AT,
      anon_sym_object,
      anon_sym_BQUOTE,
      sym_number,
      sym_string,
  [409] = 2,
    ACTIONS(86), 1,
      anon_sym_else,
    ACTIONS(84), 14,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_export,
      anon_sym_enum,
      anon_sym_if,
      anon_sym_elseif,
      anon_sym_AT,
      anon_sym_object,
      anon_sym_BQUOTE,
      sym_number,
      sym_string,
  [429] = 2,
    ACTIONS(90), 1,
      anon_sym_else,
    ACTIONS(88), 14,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_export,
      anon_sym_enum,
      anon_sym_if,
      anon_sym_elseif,
      anon_sym_AT,
      anon_sym_object,
      anon_sym_BQUOTE,
      sym_number,
      sym_string,
  [449] = 1,
    ACTIONS(92), 13,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_export,
      anon_sym_enum,
      anon_sym_if,
      anon_sym_AT,
      anon_sym_object,
      anon_sym_BQUOTE,
      sym_number,
      sym_string,
  [465] = 1,
    ACTIONS(57), 13,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_export,
      anon_sym_enum,
      anon_sym_if,
      anon_sym_AT,
      anon_sym_object,
      anon_sym_BQUOTE,
      sym_number,
      sym_string,
  [481] = 1,
    ACTIONS(94), 13,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_export,
      anon_sym_enum,
      anon_sym_if,
      anon_sym_AT,
      anon_sym_object,
      anon_sym_BQUOTE,
      sym_number,
      sym_string,
  [497] = 1,
    ACTIONS(96), 13,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_export,
      anon_sym_enum,
      anon_sym_if,
      anon_sym_AT,
      anon_sym_object,
      anon_sym_BQUOTE,
      sym_number,
      sym_string,
  [513] = 1,
    ACTIONS(98), 13,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_export,
      anon_sym_enum,
      anon_sym_if,
      anon_sym_AT,
      anon_sym_object,
      anon_sym_BQUOTE,
      sym_number,
      sym_string,
  [529] = 1,
    ACTIONS(100), 13,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_export,
      anon_sym_enum,
      anon_sym_if,
      anon_sym_AT,
      anon_sym_object,
      anon_sym_BQUOTE,
      sym_number,
      sym_string,
  [545] = 1,
    ACTIONS(102), 13,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_export,
      anon_sym_enum,
      anon_sym_if,
      anon_sym_AT,
      anon_sym_object,
      anon_sym_BQUOTE,
      sym_number,
      sym_string,
  [561] = 1,
    ACTIONS(104), 13,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_export,
      anon_sym_enum,
      anon_sym_if,
      anon_sym_AT,
      anon_sym_object,
      anon_sym_BQUOTE,
      sym_number,
      sym_string,
  [577] = 1,
    ACTIONS(106), 13,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_export,
      anon_sym_enum,
      anon_sym_if,
      anon_sym_AT,
      anon_sym_object,
      anon_sym_BQUOTE,
      sym_number,
      sym_string,
  [593] = 1,
    ACTIONS(108), 13,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_export,
      anon_sym_enum,
      anon_sym_if,
      anon_sym_AT,
      anon_sym_object,
      anon_sym_BQUOTE,
      sym_number,
      sym_string,
  [609] = 1,
    ACTIONS(110), 13,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_export,
      anon_sym_enum,
      anon_sym_if,
      anon_sym_AT,
      anon_sym_object,
      anon_sym_BQUOTE,
      sym_number,
      sym_string,
  [625] = 1,
    ACTIONS(112), 13,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_export,
      anon_sym_enum,
      anon_sym_if,
      anon_sym_AT,
      anon_sym_object,
      anon_sym_BQUOTE,
      sym_number,
      sym_string,
  [641] = 1,
    ACTIONS(114), 13,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_export,
      anon_sym_enum,
      anon_sym_if,
      anon_sym_AT,
      anon_sym_object,
      anon_sym_BQUOTE,
      sym_number,
      sym_string,
  [657] = 1,
    ACTIONS(116), 13,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_export,
      anon_sym_enum,
      anon_sym_if,
      anon_sym_AT,
      anon_sym_object,
      anon_sym_BQUOTE,
      sym_number,
      sym_string,
  [673] = 1,
    ACTIONS(118), 13,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_export,
      anon_sym_enum,
      anon_sym_if,
      anon_sym_AT,
      anon_sym_object,
      anon_sym_BQUOTE,
      sym_number,
      sym_string,
  [689] = 1,
    ACTIONS(120), 13,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_export,
      anon_sym_enum,
      anon_sym_if,
      anon_sym_AT,
      anon_sym_object,
      anon_sym_BQUOTE,
      sym_number,
      sym_string,
  [705] = 1,
    ACTIONS(122), 13,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_import,
      anon_sym_COMMA,
      anon_sym_export,
      anon_sym_enum,
      anon_sym_if,
      anon_sym_AT,
      anon_sym_object,
      anon_sym_BQUOTE,
      sym_number,
      sym_string,
  [721] = 1,
    ACTIONS(124), 9,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_EQ,
      anon_sym_BQUOTE,
  [733] = 1,
    ACTIONS(126), 9,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_EQ,
      anon_sym_BQUOTE,
  [745] = 1,
    ACTIONS(128), 9,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_EQ,
      anon_sym_BQUOTE,
  [757] = 1,
    ACTIONS(130), 9,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_GT,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_EQ,
      anon_sym_BQUOTE,
  [769] = 5,
    ACTIONS(134), 1,
      anon_sym_EQ,
    ACTIONS(136), 1,
      anon_sym_BQUOTE,
    STATE(47), 1,
      sym_object_key_default_value,
    STATE(97), 1,
      sym_object_key_tags,
    ACTIONS(132), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [786] = 5,
    ACTIONS(134), 1,
      anon_sym_EQ,
    ACTIONS(136), 1,
      anon_sym_BQUOTE,
    STATE(42), 1,
      sym_object_key_default_value,
    STATE(104), 1,
      sym_object_key_tags,
    ACTIONS(138), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [803] = 4,
    ACTIONS(140), 1,
      anon_sym_RBRACE,
    ACTIONS(142), 1,
      anon_sym_DOT,
    STATE(57), 1,
      sym_object_member,
    ACTIONS(144), 2,
      anon_sym_public,
      anon_sym_private,
  [817] = 4,
    ACTIONS(142), 1,
      anon_sym_DOT,
    ACTIONS(146), 1,
      anon_sym_RBRACE,
    STATE(78), 1,
      sym_object_member,
    ACTIONS(144), 2,
      anon_sym_public,
      anon_sym_private,
  [831] = 3,
    ACTIONS(150), 1,
      anon_sym_as,
    STATE(89), 1,
      sym__import_name_alias,
    ACTIONS(148), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [842] = 3,
    ACTIONS(136), 1,
      anon_sym_BQUOTE,
    STATE(109), 1,
      sym_object_key_tags,
    ACTIONS(152), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [853] = 4,
    ACTIONS(154), 1,
      anon_sym_GT,
    ACTIONS(156), 1,
      sym_ident,
    STATE(46), 1,
      sym_elp_type,
    STATE(61), 1,
      sym_elp_type_generic_param,
  [866] = 3,
    ACTIONS(160), 1,
      anon_sym_COMMA,
    STATE(44), 1,
      aux_sym_enum_member_repeat1,
    ACTIONS(158), 2,
      anon_sym_LBRACE,
      anon_sym_RPAREN,
  [877] = 3,
    ACTIONS(142), 1,
      anon_sym_DOT,
    STATE(82), 1,
      sym_object_member,
    ACTIONS(144), 2,
      anon_sym_public,
      anon_sym_private,
  [888] = 3,
    ACTIONS(165), 1,
      anon_sym_COLON,
    STATE(92), 1,
      sym_elp_type_generic_constraint,
    ACTIONS(163), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [899] = 3,
    ACTIONS(136), 1,
      anon_sym_BQUOTE,
    STATE(104), 1,
      sym_object_key_tags,
    ACTIONS(138), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [910] = 3,
    ACTIONS(156), 1,
      sym_ident,
    ACTIONS(167), 1,
      anon_sym_RPAREN,
    STATE(68), 1,
      sym_elp_type,
  [920] = 3,
    ACTIONS(156), 1,
      sym_ident,
    ACTIONS(169), 1,
      anon_sym_RPAREN,
    STATE(71), 1,
      sym_elp_type,
  [930] = 3,
    ACTIONS(171), 1,
      anon_sym_RBRACE,
    ACTIONS(173), 1,
      anon_sym_COMMA,
    STATE(50), 1,
      aux_sym_import_repeat1,
  [940] = 2,
    ACTIONS(178), 1,
      anon_sym_LPAREN,
    ACTIONS(176), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [948] = 3,
    ACTIONS(180), 1,
      anon_sym_RBRACE,
    ACTIONS(182), 1,
      anon_sym_COMMA,
    STATE(59), 1,
      aux_sym_enum_repeat1,
  [958] = 3,
    ACTIONS(156), 1,
      sym_ident,
    ACTIONS(184), 1,
      anon_sym_LBRACE,
    STATE(64), 1,
      sym_elp_type,
  [968] = 3,
    ACTIONS(186), 1,
      anon_sym_COMMA,
    ACTIONS(188), 1,
      anon_sym_RPAREN,
    STATE(44), 1,
      aux_sym_enum_member_repeat1,
  [978] = 3,
    ACTIONS(190), 1,
      anon_sym_RBRACE,
    ACTIONS(192), 1,
      anon_sym_COMMA,
    STATE(65), 1,
      aux_sym_object_def_repeat1,
  [988] = 3,
    ACTIONS(186), 1,
      anon_sym_COMMA,
    ACTIONS(194), 1,
      anon_sym_LBRACE,
    STATE(44), 1,
      aux_sym_enum_member_repeat1,
  [998] = 3,
    ACTIONS(190), 1,
      anon_sym_RBRACE,
    ACTIONS(192), 1,
      anon_sym_COMMA,
    STATE(66), 1,
      aux_sym_object_def_repeat1,
  [1008] = 3,
    ACTIONS(196), 1,
      anon_sym_RBRACE,
    ACTIONS(198), 1,
      anon_sym_COMMA,
    STATE(50), 1,
      aux_sym_import_repeat1,
  [1018] = 3,
    ACTIONS(200), 1,
      anon_sym_RBRACE,
    ACTIONS(202), 1,
      anon_sym_COMMA,
    STATE(59), 1,
      aux_sym_enum_repeat1,
  [1028] = 3,
    ACTIONS(182), 1,
      anon_sym_COMMA,
    ACTIONS(205), 1,
      anon_sym_RBRACE,
    STATE(52), 1,
      aux_sym_enum_repeat1,
  [1038] = 3,
    ACTIONS(207), 1,
      anon_sym_COMMA,
    ACTIONS(209), 1,
      anon_sym_GT,
    STATE(70), 1,
      aux_sym_elp_type_generic_repeat1,
  [1048] = 1,
    ACTIONS(158), 3,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1054] = 3,
    ACTIONS(211), 1,
      anon_sym_LBRACE,
    ACTIONS(213), 1,
      anon_sym_implements,
    STATE(128), 1,
      sym_object_implements,
  [1064] = 3,
    ACTIONS(186), 1,
      anon_sym_COMMA,
    ACTIONS(215), 1,
      anon_sym_LBRACE,
    STATE(56), 1,
      aux_sym_enum_member_repeat1,
  [1074] = 3,
    ACTIONS(217), 1,
      anon_sym_RBRACE,
    ACTIONS(219), 1,
      anon_sym_COMMA,
    STATE(65), 1,
      aux_sym_object_def_repeat1,
  [1084] = 3,
    ACTIONS(192), 1,
      anon_sym_COMMA,
    ACTIONS(222), 1,
      anon_sym_RBRACE,
    STATE(65), 1,
      aux_sym_object_def_repeat1,
  [1094] = 3,
    ACTIONS(198), 1,
      anon_sym_COMMA,
    ACTIONS(224), 1,
      anon_sym_RBRACE,
    STATE(58), 1,
      aux_sym_import_repeat1,
  [1104] = 3,
    ACTIONS(186), 1,
      anon_sym_COMMA,
    ACTIONS(226), 1,
      anon_sym_RPAREN,
    STATE(73), 1,
      aux_sym_enum_member_repeat1,
  [1114] = 3,
    ACTIONS(156), 1,
      sym_ident,
    STATE(46), 1,
      sym_elp_type,
    STATE(101), 1,
      sym_elp_type_generic_param,
  [1124] = 3,
    ACTIONS(207), 1,
      anon_sym_COMMA,
    ACTIONS(228), 1,
      anon_sym_GT,
    STATE(75), 1,
      aux_sym_elp_type_generic_repeat1,
  [1134] = 3,
    ACTIONS(186), 1,
      anon_sym_COMMA,
    ACTIONS(230), 1,
      anon_sym_RPAREN,
    STATE(54), 1,
      aux_sym_enum_member_repeat1,
  [1144] = 3,
    ACTIONS(232), 1,
      anon_sym_RBRACE,
    ACTIONS(234), 1,
      anon_sym_DOT,
    STATE(60), 1,
      sym_enum_member,
  [1154] = 3,
    ACTIONS(186), 1,
      anon_sym_COMMA,
    ACTIONS(236), 1,
      anon_sym_RPAREN,
    STATE(44), 1,
      aux_sym_enum_member_repeat1,
  [1164] = 2,
    ACTIONS(240), 1,
      anon_sym_PLUS,
    ACTIONS(238), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [1172] = 3,
    ACTIONS(242), 1,
      anon_sym_COMMA,
    ACTIONS(245), 1,
      anon_sym_GT,
    STATE(75), 1,
      aux_sym_elp_type_generic_repeat1,
  [1182] = 1,
    ACTIONS(247), 3,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_BQUOTE,
  [1188] = 3,
    ACTIONS(249), 1,
      anon_sym_COMMA,
    ACTIONS(251), 1,
      anon_sym_BQUOTE,
    STATE(79), 1,
      aux_sym_object_key_tags_repeat1,
  [1198] = 3,
    ACTIONS(140), 1,
      anon_sym_RBRACE,
    ACTIONS(192), 1,
      anon_sym_COMMA,
    STATE(55), 1,
      aux_sym_object_def_repeat1,
  [1208] = 3,
    ACTIONS(249), 1,
      anon_sym_COMMA,
    ACTIONS(253), 1,
      anon_sym_BQUOTE,
    STATE(80), 1,
      aux_sym_object_key_tags_repeat1,
  [1218] = 3,
    ACTIONS(255), 1,
      anon_sym_COMMA,
    ACTIONS(258), 1,
      anon_sym_BQUOTE,
    STATE(80), 1,
      aux_sym_object_key_tags_repeat1,
  [1228] = 3,
    ACTIONS(260), 1,
      anon_sym_RBRACE,
    ACTIONS(262), 1,
      sym_ident,
    STATE(67), 1,
      sym__import_name,
  [1238] = 1,
    ACTIONS(217), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1243] = 1,
    ACTIONS(264), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1248] = 2,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    STATE(15), 1,
      sym_block,
  [1255] = 1,
    ACTIONS(171), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1260] = 2,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    STATE(18), 1,
      sym_block,
  [1267] = 2,
    ACTIONS(156), 1,
      sym_ident,
    STATE(38), 1,
      sym_elp_type,
  [1274] = 2,
    ACTIONS(156), 1,
      sym_ident,
    STATE(62), 1,
      sym_elp_type,
  [1281] = 1,
    ACTIONS(266), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1286] = 1,
    ACTIONS(268), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1291] = 2,
    ACTIONS(156), 1,
      sym_ident,
    STATE(74), 1,
      sym_elp_type,
  [1298] = 1,
    ACTIONS(270), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [1303] = 2,
    ACTIONS(156), 1,
      sym_ident,
    STATE(37), 1,
      sym_elp_type,
  [1310] = 2,
    ACTIONS(272), 1,
      anon_sym_LT,
    STATE(33), 1,
      sym_elp_type_generic,
  [1317] = 2,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    STATE(7), 1,
      sym_block,
  [1324] = 2,
    ACTIONS(274), 1,
      anon_sym_BQUOTE,
    ACTIONS(276), 1,
      sym_ident,
  [1331] = 1,
    ACTIONS(138), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1336] = 2,
    ACTIONS(262), 1,
      sym_ident,
    STATE(85), 1,
      sym__import_name,
  [1343] = 1,
    ACTIONS(278), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1348] = 1,
    ACTIONS(280), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1353] = 1,
    ACTIONS(245), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [1358] = 2,
    ACTIONS(234), 1,
      anon_sym_DOT,
    STATE(108), 1,
      sym_enum_member,
  [1365] = 1,
    ACTIONS(282), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1370] = 1,
    ACTIONS(152), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1375] = 1,
    ACTIONS(284), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1380] = 2,
    ACTIONS(156), 1,
      sym_ident,
    STATE(110), 1,
      sym_elp_type,
  [1387] = 1,
    ACTIONS(286), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1392] = 1,
    ACTIONS(200), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1397] = 1,
    ACTIONS(288), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1402] = 1,
    ACTIONS(290), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [1407] = 1,
    ACTIONS(258), 2,
      anon_sym_COMMA,
      anon_sym_BQUOTE,
  [1412] = 1,
    ACTIONS(292), 1,
      anon_sym_from,
  [1416] = 1,
    ACTIONS(294), 1,
      anon_sym_LBRACE,
  [1420] = 1,
    ACTIONS(296), 1,
      sym_string,
  [1424] = 1,
    ACTIONS(298), 1,
      anon_sym_DOT,
  [1428] = 1,
    ACTIONS(300), 1,
      sym_ident,
  [1432] = 1,
    ACTIONS(302), 1,
      sym_ident,
  [1436] = 1,
    ACTIONS(304), 1,
      sym_ident,
  [1440] = 1,
    ACTIONS(306), 1,
      sym_string,
  [1444] = 1,
    ACTIONS(308), 1,
      sym_ident,
  [1448] = 1,
    ACTIONS(310), 1,
      anon_sym_LPAREN,
  [1452] = 1,
    ACTIONS(312), 1,
      sym_ident,
  [1456] = 1,
    ACTIONS(314), 1,
      sym_string,
  [1460] = 1,
    ACTIONS(316), 1,
      sym_ident,
  [1464] = 1,
    ACTIONS(318), 1,
      ts_builtin_sym_end,
  [1468] = 1,
    ACTIONS(320), 1,
      anon_sym_from,
  [1472] = 1,
    ACTIONS(322), 1,
      sym_ident,
  [1476] = 1,
    ACTIONS(324), 1,
      anon_sym_LBRACE,
  [1480] = 1,
    ACTIONS(326), 1,
      anon_sym_LBRACE,
  [1484] = 1,
    ACTIONS(328), 1,
      sym_ident,
  [1488] = 1,
    ACTIONS(330), 1,
      anon_sym_from,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 41,
  [SMALL_STATE(4)] = 81,
  [SMALL_STATE(5)] = 121,
  [SMALL_STATE(6)] = 161,
  [SMALL_STATE(7)] = 190,
  [SMALL_STATE(8)] = 219,
  [SMALL_STATE(9)] = 255,
  [SMALL_STATE(10)] = 291,
  [SMALL_STATE(11)] = 327,
  [SMALL_STATE(12)] = 353,
  [SMALL_STATE(13)] = 389,
  [SMALL_STATE(14)] = 409,
  [SMALL_STATE(15)] = 429,
  [SMALL_STATE(16)] = 449,
  [SMALL_STATE(17)] = 465,
  [SMALL_STATE(18)] = 481,
  [SMALL_STATE(19)] = 497,
  [SMALL_STATE(20)] = 513,
  [SMALL_STATE(21)] = 529,
  [SMALL_STATE(22)] = 545,
  [SMALL_STATE(23)] = 561,
  [SMALL_STATE(24)] = 577,
  [SMALL_STATE(25)] = 593,
  [SMALL_STATE(26)] = 609,
  [SMALL_STATE(27)] = 625,
  [SMALL_STATE(28)] = 641,
  [SMALL_STATE(29)] = 657,
  [SMALL_STATE(30)] = 673,
  [SMALL_STATE(31)] = 689,
  [SMALL_STATE(32)] = 705,
  [SMALL_STATE(33)] = 721,
  [SMALL_STATE(34)] = 733,
  [SMALL_STATE(35)] = 745,
  [SMALL_STATE(36)] = 757,
  [SMALL_STATE(37)] = 769,
  [SMALL_STATE(38)] = 786,
  [SMALL_STATE(39)] = 803,
  [SMALL_STATE(40)] = 817,
  [SMALL_STATE(41)] = 831,
  [SMALL_STATE(42)] = 842,
  [SMALL_STATE(43)] = 853,
  [SMALL_STATE(44)] = 866,
  [SMALL_STATE(45)] = 877,
  [SMALL_STATE(46)] = 888,
  [SMALL_STATE(47)] = 899,
  [SMALL_STATE(48)] = 910,
  [SMALL_STATE(49)] = 920,
  [SMALL_STATE(50)] = 930,
  [SMALL_STATE(51)] = 940,
  [SMALL_STATE(52)] = 948,
  [SMALL_STATE(53)] = 958,
  [SMALL_STATE(54)] = 968,
  [SMALL_STATE(55)] = 978,
  [SMALL_STATE(56)] = 988,
  [SMALL_STATE(57)] = 998,
  [SMALL_STATE(58)] = 1008,
  [SMALL_STATE(59)] = 1018,
  [SMALL_STATE(60)] = 1028,
  [SMALL_STATE(61)] = 1038,
  [SMALL_STATE(62)] = 1048,
  [SMALL_STATE(63)] = 1054,
  [SMALL_STATE(64)] = 1064,
  [SMALL_STATE(65)] = 1074,
  [SMALL_STATE(66)] = 1084,
  [SMALL_STATE(67)] = 1094,
  [SMALL_STATE(68)] = 1104,
  [SMALL_STATE(69)] = 1114,
  [SMALL_STATE(70)] = 1124,
  [SMALL_STATE(71)] = 1134,
  [SMALL_STATE(72)] = 1144,
  [SMALL_STATE(73)] = 1154,
  [SMALL_STATE(74)] = 1164,
  [SMALL_STATE(75)] = 1172,
  [SMALL_STATE(76)] = 1182,
  [SMALL_STATE(77)] = 1188,
  [SMALL_STATE(78)] = 1198,
  [SMALL_STATE(79)] = 1208,
  [SMALL_STATE(80)] = 1218,
  [SMALL_STATE(81)] = 1228,
  [SMALL_STATE(82)] = 1238,
  [SMALL_STATE(83)] = 1243,
  [SMALL_STATE(84)] = 1248,
  [SMALL_STATE(85)] = 1255,
  [SMALL_STATE(86)] = 1260,
  [SMALL_STATE(87)] = 1267,
  [SMALL_STATE(88)] = 1274,
  [SMALL_STATE(89)] = 1281,
  [SMALL_STATE(90)] = 1286,
  [SMALL_STATE(91)] = 1291,
  [SMALL_STATE(92)] = 1298,
  [SMALL_STATE(93)] = 1303,
  [SMALL_STATE(94)] = 1310,
  [SMALL_STATE(95)] = 1317,
  [SMALL_STATE(96)] = 1324,
  [SMALL_STATE(97)] = 1331,
  [SMALL_STATE(98)] = 1336,
  [SMALL_STATE(99)] = 1343,
  [SMALL_STATE(100)] = 1348,
  [SMALL_STATE(101)] = 1353,
  [SMALL_STATE(102)] = 1358,
  [SMALL_STATE(103)] = 1365,
  [SMALL_STATE(104)] = 1370,
  [SMALL_STATE(105)] = 1375,
  [SMALL_STATE(106)] = 1380,
  [SMALL_STATE(107)] = 1387,
  [SMALL_STATE(108)] = 1392,
  [SMALL_STATE(109)] = 1397,
  [SMALL_STATE(110)] = 1402,
  [SMALL_STATE(111)] = 1407,
  [SMALL_STATE(112)] = 1412,
  [SMALL_STATE(113)] = 1416,
  [SMALL_STATE(114)] = 1420,
  [SMALL_STATE(115)] = 1424,
  [SMALL_STATE(116)] = 1428,
  [SMALL_STATE(117)] = 1432,
  [SMALL_STATE(118)] = 1436,
  [SMALL_STATE(119)] = 1440,
  [SMALL_STATE(120)] = 1444,
  [SMALL_STATE(121)] = 1448,
  [SMALL_STATE(122)] = 1452,
  [SMALL_STATE(123)] = 1456,
  [SMALL_STATE(124)] = 1460,
  [SMALL_STATE(125)] = 1464,
  [SMALL_STATE(126)] = 1468,
  [SMALL_STATE(127)] = 1472,
  [SMALL_STATE(128)] = 1476,
  [SMALL_STATE(129)] = 1480,
  [SMALL_STATE(130)] = 1484,
  [SMALL_STATE(131)] = 1488,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0), SHIFT_REPEAT(129),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0), SHIFT_REPEAT(116),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0), SHIFT_REPEAT(120),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0), SHIFT_REPEAT(130),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_tree, 4, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_tree, 3, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_if_tree_repeat1, 2, 0, 0),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_if_tree_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_if_tree_repeat1, 2, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_elseif_tree, 3, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_elseif_tree, 3, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_export, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_else_block, 2, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum, 5, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum, 4, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_def, 4, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro, 4, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_tree, 5, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 5, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro, 5, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_def, 5, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 7, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 6, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum, 6, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro, 6, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_def, 6, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_def, 7, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_elp_type, 2, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_elp_type_generic, 2, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_elp_type_generic, 3, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_elp_type_generic, 4, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_member, 3, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_member, 4, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__import_name, 1, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_member, 5, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_member_repeat1, 2, 0, 0),
  [160] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enum_member_repeat1, 2, 0, 0), SHIFT_REPEAT(88),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_elp_type_generic_param, 1, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_import_repeat1, 2, 0, 0),
  [173] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_import_repeat1, 2, 0, 0), SHIFT_REPEAT(98),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_member, 2, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_implements, 1, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_implements, 3, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_enum_repeat1, 2, 0, 0),
  [202] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_enum_repeat1, 2, 0, 0), SHIFT_REPEAT(102),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_implements, 2, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_def_repeat1, 2, 0, 0),
  [219] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_object_def_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_elp_type_generic_constraint, 2, 0, 0),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [242] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_elp_type_generic_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_elp_type_generic_repeat1, 2, 0, 0),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_key_default_value, 2, 0, 0),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [255] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_object_key_tags_repeat1, 2, 0, 0), SHIFT_REPEAT(124),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_key_tags_repeat1, 2, 0, 0),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_key_tags, 4, 0, 0),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__import_name, 2, 0, 0),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_member, 4, 0, 0),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_elp_type_generic_param, 2, 0, 0),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_member, 5, 0, 0),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__import_name_alias, 2, 0, 0),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_key_tags, 2, 0, 0),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_member, 6, 0, 0),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_key_tags, 3, 0, 0),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_member, 6, 0, 0),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_elp_type_generic_constraint, 4, 0, 0),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [318] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_elp(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
